### ISSUE TITLE
Prepare server for launch

### ISSUE THREAD

**Issue by dulnan** [dulnan/drawmote#32]
### Todo
- [x] implement storing pairing codes and hashes in redis
- [x] add express-brute with redis as store
- [x] add expiration to generated pairing codes
- [x] clean up expired codes
- [x] prevent multiple devices from connecting
- [x] test websocket fallback
